title = "Echo-xorm Web Application Configuration"

secret = "jwt-super-secret"
version = "0.0.1"
# PORT for web-API of admin application
port = "11111"

[database]
# TYPE of application database
db = "mysql"
# DATA SOURCE NAME of application database
dsn = "root:123456@192.168.1.101:3306/test?charset=utf8"

[logging]
# available values "std" (or "stdout"), "fluent" (or "fluentd"), "nil" ("null")
# if not recognized then log_mode considered as "std"
log_mode = "std"
#log_tag = "your-app-tag" # if null then log_tag will be set to executable name
#id = "your-app-id" # if null then id will be set to process id
